FROM ubuntu

RUN sudo apt update

RUN sudo apt install git -y

RUN sudo apt install nginx -y

RUN sudo apt install systemctl -y

RUN sudo systemctl start nginx

RUN sudo systemctl enable nginx

WORKDIR /var/www/html

RUN sudo rm -rf index*

RUN sudo git clone https://github.com/cceliuss187/Final-Project.git

RUN sudo cp -r /var/www/html/Final-Project/* /var/www/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
